# Включает поддержку конструкции import.meta.url
parserOptions:
  ecmaVersion: 2020
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
env:
  node: true
  browser: true
rules:
# разрешает подчёркивание в именах только для двух констант
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: off
  import/extensions:
    - 'warn'
    - 'ignorePackages'
    - js: always
  linebreak-style: ["error", "unix"]
